valor=input('Digite algo ')
print('o tipo primitivo desse valor é ', type(valor))
print('o valor é alfanumérico ', valor.isalnum())
print('o valor é alfabético ', valor.isalpha())
print('o valor é numérico ', valor.isnumeric())
print('o valor é caixa alta ', valor.isupper())
print('o valor é caixa baixa ', valor.islower())
